version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      tags:
        - ozon
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./config:/root/config
    profiles:
      - postgres
    networks:
      - postgres-net
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    profiles:
      - postgres
    networks:
      - postgres-net
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - postgres
    networks:
      - postgres-net
    profiles:
      - postgres
  in_memory:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./config:/root/config
    ports:
      - "8080:8080"
    profiles:
      - in-memory
networks:
  postgres-net: