// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              string     `json:"id"`
	PostID          string     `json:"postId"`
	ParentCommentID *string    `json:"parentCommentId,omitempty"`
	AuthorID        string     `json:"authorId"`
	Content         string     `json:"content"`
	CreatedAt       string     `json:"createdAt"`
	UpdatedAt       string     `json:"updatedAt"`
	Replies         []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID                 string     `json:"id"`
	AuthorID           string     `json:"authorId"`
	Content            string     `json:"content"`
	AreCommentsAllowed bool       `json:"areCommentsAllowed"`
	CreatedAt          string     `json:"createdAt"`
	UpdatedAt          string     `json:"updatedAt"`
	Comments           []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type CreatePostInput struct {
	AuthorID           string `json:"authorId"`
	Content            string `json:"content"`
	AreCommentsAllowed bool   `json:"areCommentsAllowed"`
}

type PostCommentInput struct {
	PostID          string  `json:"postId"`
	ParentCommentID *string `json:"parentCommentId,omitempty"`
	AuthorID        string  `json:"authorId"`
	Content         string  `json:"content"`
}

type PutCommentInput struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

type PutPostInput struct {
	ID                 string  `json:"id"`
	Content            *string `json:"content,omitempty"`
	AreCommentsAllowed *bool   `json:"areCommentsAllowed,omitempty"`
}
